# Generated by Django 5.0.3 on 2024-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('User_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('User_passwd', models.CharField(max_length=12)),
            ],
        ),
    ]
