# Generated by Django 5.0.3 on 2024-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='User_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='User_passwd',
            field=models.CharField(max_length=120),
        ),
    ]
